version: '3'
services:
  nest-library-db:
    container_name: nest-library-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=nest_library'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'
